- name: Copy docker release packages to local_package_dir
  copy:
    src=files/docker-{{ docker_major_version }}.{{ docker_minor_version }}-ce.tgz
    dest={{ local_package_dir }}/
  connection=local

- name: Unarchived kubernetes file
  unarchive:
    src={{ local_package_dir }}/docker-{{ docker_major_version }}.{{ docker_minor_version }}-ce.tgz
    dest={{ local_package_dir }}/
    copy=no
  connection=local

- name: Distribute binary file
  copy:
    src={{ local_package_dir }}/docker/
    dest={{ package_dir }}/bin/
    owner={{ k8s_user }}

- name: Distribute docker service file
  copy:
    src=templates/docker.service.template
    dest=/etc/systemd/system/ocker.service

- name: Distribute docker-daemon config file
  copy:
    src=templates/docker-daemon.json.template
    dest={{ docker_conf_dir }}/daemon.json

- name: Start docker service
  service:
    name=docker
    state=started
    enabled=yes