- name: Create kubelet lib dir
  file:
    path=/var/lib/kubelet
    state=directory

- name: Distribute binary file
  copy:
    src={{ local_package_dir }}/kubernetes/server/bin/
    dest={{ package_dir }}/bin/
    owner={{ k8s_user }}

- name: Create token
  shell:
    kubeadm token create --description kubelet-bootstrap-token --groups system:bootstrappers:{{ node_name }} --kubeconfig {{ local_template_dir }}/kubectl.kubeconfig > {{ node_name }}.token
  connection: local
  ignore_errors: yes

- name: Configure k8s cluster parameter
  shell:
    cd {{ local_template_dir }} && {{ local_package_dir }}/kubectl/kubernetes/client/bin/kubectl config set-cluster kubernetes --certificate-authority=ca.pem --embed-certs=true --server={{ kube_apiserver }} --kubeconfig=kubelet-bootstrap-{{ node_name }}.kubeconfig
  connection: local
  ignore_errors: yes

- name: Configure k8s client certificate parameter
  shell:
    cd {{ local_template_dir }} && {{ local_package_dir }}/kubectl/kubernetes/client/bin/kubectl config set-credentials kubelet-bootstrap --token=`cat {{ node_name }}.token` --kubeconfig=kubelet-bootstrap-{{ node_name }}.kubeconfig
  connection: local
  ignore_errors: yes

- name: Configure context parameter
  shell:
    cd {{ local_template_dir }} && {{ local_package_dir }}/kubectl/kubernetes/client/bin/kubectl config set-context default --cluster=kubernetes --user=kubelet-bootstrap --kubeconfig=kubelet-bootstrap-{{ node_name }}.kubeconfig
  connection: local
  ignore_errors: yes

- name: Configure use-context
  shell:
    cd {{ local_template_dir }} && {{ local_package_dir }}/kubectl/kubernetes/client/bin/kubectl config use-context default --kubeconfig=kubelet-bootstrap-{{ node_name }}.kubeconfig
  connection: local
  ignore_errors: yes

- name: Distribute kubelet file to user k8s
  copy:
    src={{ local_template_dir }}/kubelet-bootstrap-{{ node_name }}.kubeconfig
    dest={{ kubernetes_conf_dir }}/kubelet-bootstrap.kubeconfig
    owner={{ k8s_user }}

- name: Distribute kubelet parameter config file
  template:
    src=templates/kubelet.config.json.j2
    dest={{ kubernetes_conf_dir }}/kubelet.config.json

- name: Distribute kubelet service file
  template:
    src=templates/kubelet.service.j2
    dest=/etc/systemd/system/kubelet.service

- name: Create clusterrole binding
  shell:
    ssh root@{{ master_vip }}"kubectl create clusterrolebinding kubelet-bootstrap --clusterrole=system:node-bootstrapper --group=system:bootstrappers"
  connection: local
  ignore_errors: yes

- name: Start kubelet service
  service:
    name=kubelet
    state=started
    enabled=yes

- name: Copy csr-crb file
  copy:
    src=templates/csr-crb.yaml.template
    dest={{ package_dir }}/csr-crb.yaml

- name: Apply csr-crb
  shell:
    kubectl apply -f {{ package_dir }}/csr-crb.yaml
