- name: Copy docker release packages to local_package_dir
  copy:
    src=files/docker-{{ docker_version }}-ce.tgz
    dest={{ local_package_dir }}/
  connection: local
  ignore_errors: yes

- name: Unarchived kubernetes file
  unarchive:
    src={{ local_package_dir }}/docker-{{ docker_version }}-ce.tgz
    dest={{ local_package_dir }}/
    copy=no
  connection: local
  ignore_errors: yes

- name: Distribute binary file
  copy:
    src={{ local_package_dir }}/docker/
    dest={{ package_dir }}/bin/
    owner={{ k8s_user }}
    mode=0755

- name: Distribute docker service file
  template:
    src=templates/docker.service.j2
    dest=/etc/systemd/system/docker.service

- name: Distribute docker-daemon config file
  template:
    src=templates/docker-daemon.json.j2
    dest={{ docker_conf_dir }}/daemon.json

- name: Start docker service
  service:
    name=docker
    state=started
    enabled=yes